definitions:
  bandgo.BandUser:
    properties:
      ID:
        description: 主键ID
        type: integer
      account_status:
        type: string
      avatar:
        type: string
      bio:
        type: string
      city:
        type: string
      country:
        type: string
      cover_image_url:
        type: string
      createdAt:
        description: 创建时间
        type: string
      date_of_birth:
        type: string
      email:
        type: string
      enable:
        type: integer
      full_name:
        type: string
      is_pro_user:
        type: boolean
      last_login_at:
        type: string
      location:
        type: string
      nickname:
        type: string
      notification_preferences:
        description: swagger:strfmt json
        items:
          type: integer
        type: array
      openid:
        description: 添加微信相关字段
        type: string
      phone:
        type: string
      preferred_language:
        type: string
      profile_image_url:
        type: string
      province:
        type: string
      sex:
        type: integer
      social_links:
        description: swagger:strfmt json
        items:
          type: integer
        type: array
      unionid:
        type: string
      updatedAt:
        description: 更新时间
        type: string
      username:
        type: string
      uuid:
        type: string
      verification_status:
        type: boolean
    type: object
  bandgo.BandUserSkill:
    properties:
      ID:
        description: 主键ID
        type: integer
      createdAt:
        description: 创建时间
        type: string
      instrument_id:
        type: integer
      is_primary:
        type: boolean
      skill_description:
        type: string
      skill_level:
        type: string
      updatedAt:
        description: 更新时间
        type: string
      user_id:
        type: integer
      years_experience:
        type: integer
    type: object
  github_com_flipped-aurora_gin-vue-admin_server_model_bandgo_request.Login:
    properties:
      captcha:
        description: 验证码
        type: string
      captchaId:
        description: 验证码ID
        type: string
      password:
        description: 密码
        type: string
      username:
        description: 用户名
        type: string
    type: object
  github_com_flipped-aurora_gin-vue-admin_server_model_bandgo_request.Register:
    properties:
      email:
        type: string
      fullName:
        type: string
      password:
        type: string
      username:
        type: string
    type: object
  github_com_flipped-aurora_gin-vue-admin_server_model_bandgo_response.LoginResponse:
    properties:
      token:
        type: string
      user:
        $ref: '#/definitions/bandgo.BandUser'
    type: object
  github_com_flipped-aurora_gin-vue-admin_server_model_bandgo_response.SysCaptchaResponse:
    properties:
      captchaId:
        type: string
      captchaLength:
        type: integer
      openCaptcha:
        type: boolean
      picPath:
        type: string
    type: object
  model.Info:
    properties:
      ID:
        description: 主键ID
        type: integer
      attachments:
        description: 附件
        items:
          type: object
        type: array
      content:
        description: 内容
        type: string
      createdAt:
        description: 创建时间
        type: string
      title:
        description: 标题
        type: string
      updatedAt:
        description: 更新时间
        type: string
      userID:
        description: 作者
        type: integer
    type: object
  request.Configer:
    properties:
      url:
        type: string
    type: object
  request.UpdateProfile:
    properties:
      bio:
        type: string
      coverImageURL:
        type: string
      location:
        type: string
      phoneNumber:
        type: string
      profileImageURL:
        type: string
    type: object
  request.WXLogin:
    properties:
      code:
        description: 授权码
        type: string
    type: object
  response.Email:
    properties:
      body:
        description: 邮件内容
        type: string
      subject:
        description: 邮件标题
        type: string
      to:
        description: 邮件发送给谁
        type: string
    type: object
  response.PageResult:
    properties:
      list: {}
      page:
        type: integer
      pageSize:
        type: integer
      total:
        type: integer
    type: object
  response.Response:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
  response.WeiXinConfigResponse:
    properties:
      appId:
        type: string
      nonceStr:
        type: string
      signature:
        type: string
      timestamp:
        type: string
    type: object
  response.WeiXinLoginResponse:
    properties:
      appId:
        type: string
      nonceStr:
        type: string
      signature:
        type: string
      timestamp:
        type: string
    type: object
info:
  contact: {}
  description: 使用gin+vue进行极速开发的全栈开发基础平台
  title: Band Go Swagger API接口文档
  version: v1.0.0 from gin-vue-admin v2.7.9
paths:
  /base/captcha:
    post:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 生成验证码,返回包括随机数id,base64,验证码长度,是否开启验证码
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/github_com_flipped-aurora_gin-vue-admin_server_model_bandgo_response.SysCaptchaResponse'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 生成验证码
      tags:
      - Base
  /base/wx/config:
    post:
      consumes:
      - application/json
      parameters:
      - description: URL
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.Configer'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.WeiXinConfigResponse'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 微信配置
      tags:
      - WeinXin
  /base/wx/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: code
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.WXLogin'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.WeiXinLoginResponse'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 微信登录
      tags:
      - WeinXin
  /email/emailTest:
    post:
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"发送成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 发送测试邮件
      tags:
      - System
  /email/sendEmail:
    post:
      parameters:
      - description: 发送邮件必须的参数
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/response.Email'
      produces:
      - application/json
      responses:
        "200":
          description: '{"success":true,"data":{},"msg":"发送成功"}'
          schema:
            type: string
      security:
      - ApiKeyAuth: []
      summary: 发送邮件
      tags:
      - System
  /info/createInfo:
    post:
      consumes:
      - application/json
      parameters:
      - description: 创建公告
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Info'
      produces:
      - application/json
      responses:
        "200":
          description: 创建成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 创建公告
      tags:
      - Info
  /info/deleteInfo:
    delete:
      consumes:
      - application/json
      parameters:
      - description: 删除公告
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Info'
      produces:
      - application/json
      responses:
        "200":
          description: 删除成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 删除公告
      tags:
      - Info
  /info/deleteInfoByIds:
    delete:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 批量删除成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 批量删除公告
      tags:
      - Info
  /info/findInfo:
    get:
      consumes:
      - application/json
      parameters:
      - description: 主键ID
        in: query
        name: ID
        type: integer
      - description: 内容
        in: query
        name: content
        type: string
      - description: 创建时间
        in: query
        name: createdAt
        type: string
      - description: 标题
        in: query
        name: title
        type: string
      - description: 更新时间
        in: query
        name: updatedAt
        type: string
      - description: 作者
        in: query
        name: userID
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: 查询成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/model.Info'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 用id查询公告
      tags:
      - Info
  /info/getInfoDataSource:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: 查询成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
                msg:
                  type: string
              type: object
      summary: 获取Info的数据源
      tags:
      - Info
  /info/getInfoList:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        name: endCreatedAt
        type: string
      - description: 关键字
        in: query
        name: keyword
        type: string
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页大小
        in: query
        name: pageSize
        type: integer
      - in: query
        name: startCreatedAt
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/response.PageResult'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 分页获取公告列表
      tags:
      - Info
  /info/getInfoPublic:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        name: endCreatedAt
        type: string
      - description: 关键字
        in: query
        name: keyword
        type: string
      - description: 页码
        in: query
        name: page
        type: integer
      - description: 每页大小
        in: query
        name: pageSize
        type: integer
      - in: query
        name: startCreatedAt
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: 获取成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  type: object
                msg:
                  type: string
              type: object
      summary: 不需要鉴权的公告接口
      tags:
      - Info
  /info/updateInfo:
    put:
      consumes:
      - application/json
      parameters:
      - description: 更新公告
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/model.Info'
      produces:
      - application/json
      responses:
        "200":
          description: 更新成功
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 更新公告
      tags:
      - Info
  /user/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名, 密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/github_com_flipped-aurora_gin-vue-admin_server_model_bandgo_request.Login'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/github_com_flipped-aurora_gin-vue-admin_server_model_bandgo_response.LoginResponse'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 用户登录
      tags:
      - User
  /user/profile:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/bandgo.BandUser'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 获取用户信息
      tags:
      - BandUser
    put:
      consumes:
      - application/json
      parameters:
      - description: 用户信息
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.UpdateProfile'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 更新用户信息
      tags:
      - User
  /user/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: 用户名, 密码, 邮箱
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/github_com_flipped-aurora_gin-vue-admin_server_model_bandgo_request.Register'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  $ref: '#/definitions/bandgo.BandUser'
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 用户注册
      tags:
      - User
  /user/skills:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            allOf:
            - $ref: '#/definitions/response.Response'
            - properties:
                data:
                  items:
                    $ref: '#/definitions/bandgo.BandUserSkill'
                  type: array
                msg:
                  type: string
              type: object
      security:
      - ApiKeyAuth: []
      summary: 获取用户技能列表
      tags:
      - User
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
tags:
- name: Base
